name: jenkins-trigger
name: trigger jenkins job
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: trigger single Job
      uses: appleboy/jenkins-action@master
      with:
        url: "http://pulkit.cloudspace.com"
        user: "Ankit"
        token: ${{ secrets.TOKEN }}
        job: "22ndseptember"
